# Generated by Django 3.1 on 2020-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='deadline',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photo',
            name='deadline',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
