# Generated by Django 3.1 on 2020-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200901_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='deadline',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deadline',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
