# Generated by Django 3.1 on 2020-08-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200901_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='deadline',
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.ImageField(null=True, upload_to='images/')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form3', to='upload.form')),
            ],
        ),
    ]
