# Generated by Django 3.1 on 2020-09-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200901_0111'),
    ]

    operations = [
    ]
