# Generated by Django 3.1 on 2020-09-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_testuserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testuserprofile',
            old_name='user',
            new_name='사용자',
        ),
    ]
