# Generated by Django 3.1 on 2020-09-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200903_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testuserprofile',
            old_name='사용자',
            new_name='user',
        ),
    ]
