# Generated by Django 3.1 on 2020-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200903_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testuserprofile',
            old_name='address',
            new_name='주소',
        ),
        migrations.RemoveField(
            model_name='testuserprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='testuserprofile',
            name='전화번호',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testuserprofile',
            name='주민등록번호',
            field=models.CharField(default='', max_length=20),
        ),
    ]
