# Generated by Django 3.1 on 2020-09-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200904_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testuserprofile',
            old_name='주소',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='testuserprofile',
            old_name='전화번호',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='testuserprofile',
            old_name='주민등록번호',
            new_name='registration_number',
        ),
    ]
