# Generated by Django 3.1.1 on 2020-09-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200, null=True)),
                ('group', models.CharField(max_length=200, null=True)),
                ('total_money', models.CharField(max_length=200, null=True)),
                ('contents', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mileage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage2', to='mileage.mileage')),
            ],
        ),
    ]
