# Generated by Django 3.1 on 2020-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='donate_money',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
