# Generated by Django 3.1 on 2020-09-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0002_mileage_donate_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileage',
            name='donate_money',
        ),
    ]
