# Generated by Django 3.1 on 2020-09-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0003_remove_mileage_donate_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
