# Generated by Django 3.1 on 2020-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0004_auto_20200913_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='total_money',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
